services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - ELASTIC_PASSWORD=myelasticpass
      - KIBANA_PASSWORD=kibanapass
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "path.repo=/usr/share/elasticsearch/backup"
    ports:
      - 9200:9200
    volumes:
      - ./elk/data:/usr/share/elasticsearch/data
      - ./elk/backup:/usr/share/elasticsearch/backup

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: kibanapass
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: "a7a6311933d3503b89bc2dbc36572c33a6c10925682e591bffcab6911c06786d"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
      
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.12.2
    command: filebeat -e -strict.perms=false
    volumes:
      - ./elk/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /home/tydv/Documents:/var/log:ro
      - ./elk/filebeat_data:/usr/share/filebeat/data
  
  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.2
    volumes:
      - ./elk/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    environment:
      - xpack.monitoring.enabled=false
      - xpack.management.enabled=false
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=myelasticpass
      - ELASTIC_HOSTS=http://elasticsearch:9200
    ports:
      - 5044:5044
      - 9600:9600
