services:
  cassandra:
    image: cassandra:3.11.17
    container_name: cassandra-container
    ports:
      - "9042:9042"
      - "7070:7070"
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
    volumes:
      - ./cassandradata:/var/log/cassandra #mount log của cassandra 
      - ./jmx_exporter/jmx_prometheus_javaagent-0.18.0.jar:/jmx_exporter/jmx_prometheus_javaagent-0.18.0.jar
      - ./config/jmx_config.yml:/jmx_exporter/jmx_config.yaml
      - ./jmx_exporter/cassandra-env.sh:/etc/cassandra/cassandra-env.sh #mount 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - ELASTIC_PASSWORD=myelasticpass
      - KIBANA_PASSWORD=kibanapass
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ports:
      - 9200:9200
    volumes:
      - ./elkdata/data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: kibanapass
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: "a7a6311933d3503b89bc2dbc36572c33a6c10925682e591bffcab6911c06786d"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
      
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.12.2
    command: filebeat -e -strict.perms=false
    volumes:
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./cassandradata:/var/log:ro
      - ./elkdata/filebeat_data:/usr/share/filebeat/data
  
  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.2
    volumes:
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    environment:
      - xpack.monitoring.enabled=false
      - xpack.management.enabled=false
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=myelasticpass
      - ELASTIC_HOSTS=http://elasticsearch:9200
    ports:
      - 5044:5044
      - 9600:9600
    depends_on:
      - filebeat
  #Giám sát máy host (node)
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    ports:
      - "9100:9100" 
    volumes:
      - '/:/host:ro,rslave'  
    command:
      - '--path.rootfs=/host'  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"  
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml  
      - prometheus-data:/prometheus  
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - node-exporter  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"  
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus  
volumes:
  prometheus-data:
  grafana-data:
