global:
  resolve_timeout: 5m  # Thời gian chờ để đánh dấu một cảnh báo đã được giải quyết
  smtp_smarthost: 'mail.atalink.vn:465'  # Máy chủ SMTP để gửi email
  smtp_from: 'tydv@atalink.vn'     # Email gửi đi
  smtp_auth_username: 'tydv@atalink.vn'  # Tài khoản email
  smtp_auth_password: ''
  smtp_require_tls: false


route:
  receiver: 'slack'  # Định nghĩa receiver mặc định
  group_by: ['alertname']  # Gom nhóm cảnh báo theo alertname
  group_wait: 10s          # Thời gian chờ để gom nhóm cảnh báo
  group_interval: 2m       # Khoảng thời gian giữa các cảnh báo trong cùng nhóm
  repeat_interval: 1h      # Thời gian lặp lại gửi thông báo nếu cảnh báo vẫn chưa được giải quyết

  routes: 
    - match:
        severity: 'critical'
      receiver: 'slack'
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 1h
receivers:
  - name: 'warning-alert'
    email_configs:
      - to: 'dinhvanty206@gmail.com'  # Email người nhận cảnh báo
        send_resolved: true
  - name: 'critical-email'
    email_configs:
      - to: 'n20dccn070@student.ptithcm.edu.vn'
  - name: 'slack'
    slack_configs:
      - api_url: https://hooks.slack.com/services/T0868SWPUFP/B086EDDNWJG/L
        channel: '#a-project'
        send_resolved: true
        title: '{{ .CommonLabels.alertname }}'
        text: |
          Alerts: {{ range .Alerts }}
            - Status: {{ .Status }}
              SEVERITY: {{ .Labels.severity }}
              Description: {{ .Annotations.description }}
          {{ end }}
        
  