services:
  # Node Exporter - Thu thập số liệu về máy chủ
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    ports:
      - "9100:9100" 
    volumes:
      - '/:/host:ro,rslave'  # Mount root filesystem vào container để thu thập dữ liệu
    command:
      - '--path.rootfs=/host'  # Chỉ định root filesystem cho node-exporter
    networks:
      - monitoring

  # Prometheus - Thu thập và lưu trữ số liệu
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"  
    volumes:
      - /home/tydv/Project/Demo_prometheus/prometheus.yml:/etc/prometheus/prometheus.yml  # Đường dẫn tới file cấu hình Prometheus
      - /home/tydv/Project/Demo_prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml  # File rules cảnh báo
      - prometheus-data:/prometheus  # Mount volume để lưu trữ dữ liệu Prometheus
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - node-exporter  
    networks:
      - monitoring

  # Grafana - Giao diện web để hiển thị số liệu
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"  # Mở cổng 3000 cho Grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Mật khẩu của admin trong Grafana
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus  
    networks:
      - monitoring
  # Alertmanager - Xử lý cảnh báo từ Prometheus
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    ports:
      - "9093:9093"  
    volumes:
      - /home/tydv/Project/Demo_prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml  # Đường dẫn tới file cấu hình Alertmanager
      - alertmanager-data:/alertmanager  # Mount volume để lưu trữ dữ liệu Alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    networks:
      - monitoring
  # Nginx 
  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    restart: unless-stopped
    ports:
      - "80:80"       # HTTP
      - "443:443"     # HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount file cấu hình Nginx
      - ./ssl:/etc/nginx/ssl                  # Mount thư mục chứa chứng chỉ SSL
    depends_on:
      - grafana  
    networks:
      - monitoring
# Tạo volume để lưu trữ dữ liệu Prometheus
volumes:
  prometheus-data:
  grafana-data:
  alertmanager-data:

# Tạo mạng Docker riêng biệt cho các container
networks:
  monitoring:
    driver: bridge

