global:
  scrape_interval: 15s  # Thời gian quét mặc định là 15 giây
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']

rule_files:
  - 'alert_rules.yml'
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'